---
- hosts: localhost
  gather_facts: false
  vars:
     region: ap-south-1
     instace_type: t2.micro
     ami: ami-5b673c34
     keypair: desh
  tasks:
  - name: "create new ec2 instance"
    ec2:
      key_name: "{{ keypair }}"
      instance_type: "{{ instace_type }}"
      image: "{{ ami }}"
      region: "{{ region }}"
      group: "launch-wizard-4"
      aws_access_key: "{{ aws_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      wait: true
      count: 1
      count_tag:
        name: "Demo"
      instance_tags:
        name: "Demo"
      vpc_subnet_id: subnet-e6de8f8e
      assign_public_ip: yes
    register: ec2
  - name: "print ec2 module output"
    debug: var=ec2

  - debug:
      msg: "{{ item['private_ip'] }}"
    with_items: "{{ ec2.instances }}"
  - set_fact: ip_list= "[]"

  - name: construct ip address
    set_fact: ip_list= " ['{{ item.private_ip }}']"
    with_items: "{{ ec2.instances }}"
  - name: print Ip address
    debug: msg= "{{ ip_list }}"
  
