--- 
- 
  become: true
  handlers: 
    - 
      name: "restart tomcat"
      service: 
        name: tomcat7
        state: restarted
  hosts: ubuntu
  tasks: 
    - 
      apt: 
        name: tomcat7
        state: present
        update_cache: true
      notify: restart tomcat
    - 
      copy: 
        dest: /home/ubuntu/
        src: /opt/ansible-demo/deshTest/test.txt
        notify: restart tomcat
