---
# tasks file for jenkin

- name: "installing java first"
  become: true
  yum:
    name: java
    state: latest
   
- name: "adding jenkins repos"
  get_url:
    url: https://pkg.jenkins.io/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: true
- name: "import rpm key for jenkins"
  rpm_key:
    state: present
    key: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
  become: true
- name: "installling jenkins"
  yum:
    name: jenkins
    state: latest
  become: true   
 
