---
- hosts: localhost
  gather_facts: false
 
  tasks:
  - name: "Creating ec2 instances"
    ec2:
      key_name: "{{ key_name }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      count: "{{ count }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: "{{ assign_public_ip }}"
      region: "{{ region}}"
    register: ec2
  - name: "printing ec2 module output" 
    debug: var=ec2
    
  - name: "printing ip adress"
    debug: 
      msg: "{{ item['private_ip'] }}"
    with_items: "{{ ec2.instances }}"
           
